### ISSUE TITLE
Missing exception on 'Performance Tips' page

### ISSUE THREAD

**Issue by pjbeardsley** [flourishlib/flourish-classes#121]
Ticket #702 by @bluematt

The [fAuthorizationException](http://flourishlib.com/docs/fAuthorizationException) class is missing from the list of exceptions to load in the Class Loading section.

http://flourishlib.com/docs/PerformanceTips#ClassLoading

**Comment by wbond** [comment]
This is now out-of-date since that page no longer includes such information.
