### ISSUE TITLE
feature request: http class

### ISSUE THREAD

**Issue by hanoii** [flourishlib/flourish-classes#171]
Class for making with http requests, post request, follow redirections, etc. Might be an useful class to add.

**Comment by Dazzel** [comment]
Does already exists; fRequest.

**Comment by hanoii** [comment]
fRequest is for dealing with http request, I was more meaning to "making¨ http request, either via curl or some other method so you could retrieve a file or interact with a REST API for instance.

**Comment by wbond** [comment]
This is a duplicate of #9
