### ISSUE TITLE
Accept */* at end as equivalent to first argument in getBestAcceptType()

### ISSUE THREAD

**Issue by Tatsh** [flourishlib/flourish-classes#69]
IE < 9 sometimes (completely random) sends this stupid Accept header:

`image/jpeg, application/x-ms-application, image/gif, application/xaml+xml, image/pjpeg, application/x-ms-xbap, application/msword, application/vnd.ms-excel, application/x-shockwave-flash, */*`

so a call like `fRequest::getBestAcceptType('text/html')` returns `FALSE`. I think it should still return `'text/html'` because there is a `*/*` at the end.

**Comment by mattsah** [comment]
I would like to first note, you are correct that it is a "stupid Accept Header."  Secondly, however, I would have to assume maybe this is a bug?  Unless I've read the spec wrong, but because of the `*/*` it **should** be returning `text/html`.

**Comment by Tatsh** [comment]
Well, the documentation is seemingly correct however:

``` php
<?php
/**
     * Special conditions affecting the return value:
     *  - If no `$filter` is provided and the client does not send the `Accept` header, `NULL` will be returned
     *  - If no `$filter` is provided and the client specifies `{@*}*` with the highest `q`, `NULL` will be returned
     *  - If `$filter` contains one or more values, but the `Accept` header does not match any, `FALSE` will be returned
     *  - If `$filter` contains one or more values, but the client does not send the `Accept` header, the first entry from `$filter` will be returned
     *  - If `$filter` contains two or more values, and two of the values have the same `q` value, the one listed first in `$filter` will be returned
*/
```

So, in the case of this header where `*/*` is at the end, it is not the highest 'q' value and therefore `FALSE` is returned. The documentation does not say that if `*/*` appears anywhere in the header that the first type passed will be returned. That is what I think should be revised.

**Comment by mattsah** [comment]
@tatsh I was referring to the HTTP documentation regarding the Accept header handling.  If a given mimetype is not acceptable, it's q value should not come into play at all.  In short, I'm saying I think Flourish is not matching the RFC which provides the following definition:

```
A more elaborate example is

       Accept: text/plain; q=0.5, text/html,
               text/x-dvi; q=0.8, text/x-c

Verbally, this would be interpreted as "text/html and text/x-c are the preferred media types, but if they do not exist, then send the text/x-dvi entity, and if that does not exist, send the text/plain entity." 
```

In the above example text/html and text/x-c both have an implied q value of 1.

Additionally, the the precedences of multiple matching media types with the same q value, implied or otherwise follows this rule:

```
Media ranges can be overridden by more specific media ranges or specific media types. If more than one media range applies to a given type, the most specific reference has precedence. For example,

       Accept: text/*, text/html, text/html;level=1, */*

have the following precedence:

       1) text/html;level=1
       2) text/html
       3) text/*
       4) */*
```

Flourishes documentation is right, but it's logic is wrong (or at least incomplete)... or so it seems to me.

**Comment by mattsah** [comment]
@tatsh 

The above changes which include my previous changes, and whitespace changes again fix this issue.  If you want to add the change separately just for this issue, all it is is wrapping $type in trim(), code looks like the following at ~ line 768

``` php
foreach ($output as $type => $q) {
     $output[trim($type)] = (float) substr($q, 0, -1);
}
```

Here's the output from my console showing it working:

```
[/Users/matts/inkwell][01]# $_SERVER['HTTP_ACCEPT'] = 'image/jpeg, application/x-ms-application, image/gif, application/xaml+xml, image/pjpeg, application/x-ms-xbap, application/msword, application/vnd.ms-excel, application/x-shockwave-flash, */*';
[/Users/matts/inkwell][01]# var_dump(fRequest::getBestAcceptType('text/html'));
string(9) "text/html"
```

**Comment by Tatsh** [comment]
I'll test it in about 5 days when I get back to my place. I'll also send a cleaner patch. Otherwise, +1
