### ISSUE TITLE
Deleting object in many-to-many relationship without class

### ISSUE THREAD

**Issue by jeffturcotte** [flourishlib/flourish-classes#88]
Ticket #679 by unstoppablecarl

When trying to delete something that has some many-to-many relationships with tables I don't have a class for I get an error. It would be nice to be able to suppress that instead of have to make an empty class.

**Comment by jeffturcotte** [comment]
This seems like a horrible idea. Should be a wontfix.

**Comment by cidic** [comment]
I wrote that a long time ago and didn't really understand what was happening and agree with you :)

**Comment by jeffturcotte** [comment]
:) Closing!
